name: main
on:
  push:
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cypress E2E tests 🧪
        uses: cypress-io/github-action@v5
        with:
          start: npm start

  component-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cypress component tests 🧪
        uses: cypress-io/github-action@v5
        with:
          component: true
